# -*- coding: utf-8 -*-
"""Boy or Girl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TjkBIyrokI8d5CbsJa-CukOJ8RarhjyZ
"""

name = input()
char = []
if name.islower():
  name=list(set(name))
  if len(name)%2 == 0:
    print("CHAT WITH HER!")
  else:
    print("IGNORE HIM!")
else:
  print("IGNORE HIM!")

