# -*- coding: utf-8 -*-
"""Watermelon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_Ee44F0gprmP-M1tTmpoWYBRDbXkuS0
"""

data= int(input())
if data % 2 == 0 and  data > 2  :
  print("Yes")
else:
  print("No")

