# -*- coding: utf-8 -*-
"""Word Capitalization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_Ee44F0gprmP-M1tTmpoWYBRDbXkuS0
"""

data= input()
if data[0].islower():
  data= data[0].upper() + data[1:]
  print(data)
else:
  print(data)

